Repository JhnonathaCastanhal/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: Análise v1.1

#4 Integrar arquitetura v1.1
  docs/arquitetura v1.1.md
Labels: Arquitetura v1.1

#6 Integrar implementação v1.1
  src/jogovelha.py
Labels: Programação v1.1

#9 Gerar release V1.1
  docs/arquitetura v1.1.md
  docs/requisitos.md
  src/jogovelha.py
  src/teste_jogar.py
  src/testes_inic.py
Labels: Operações v1.1
